#!/bin/sh
#
# http://blog.andrewbeacock.com/2009/10/how-to-get-scala-working-with-rxvt.html
# http://stackoverflow.com/questions/4468967/two-problems-with-sbt-in-cygwin-vista
#dir=`dirname $0`
#java -Xmx512M -jar `cygpath -w $dir`/sbt-launch.jar "$@"

#must be saved with unix line endings
#setup for using sbt with cygwin's mintty terminal (gets you colored specs2 tests)

BASEDIR=$(dirname $0)
stty -icanon min 1 -echo > /dev/null 2>&1
java -Djline.terminal=jline.UnixTerminal -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Xmx512M -Xss2M -jar `cygpath -m $BASEDIR/sbt-launch.jar` "$@"
stty icanon echo > /dev/null 2>&1

