" Helpful links:
" http://amix.dk/vim/vimrc.html
" http://stackoverflow.com/questions/164847/what-is-in-your-vimrc

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Use vim defaults
set nocompatible

" History
set history=100

" Enable filetype plugin
filetype plugin on
filetype indent on
syntax on

" Status line
set ruler
set showmode
set wildmenu
set laststatus=2

" Editing
set completeopt=menu,longest,preview
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
" set formatoptions+=tcrql

" Search
set ignorecase
set smartcase
set hlsearch
set incsearch
set matchtime=5

" Brackets
set showmatch

" No sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Tabs and spaces
set smarttab
set expandtab
set softtabstop=4
set tabstop=4 
set listchars=tab:>-,trail:-

" Indents
set autoindent
set smartindent
set shiftwidth=4
set shiftround
set copyindent
set preserveindent

" Folds
set foldcolumn=2
set foldmethod=indent

" Allow command mode w/o shift
nore ; :
nore , ;

" Cursor
set scrolloff=1
set whichwrap+=b,s,<,>,[,]

" Misc
set nobackup
set shell=zsh
set virtualedit=block
set lazyredraw

" Commands

" Remap broken meta-keys that send ^[
for n in range(97,122) " ASCII a-z
    let c = nr2char(n)
    exec "set <M-". c .">=\e". c
    exec "map  \e". c ." <M-". c .">"
    exec "map! \e". c ." <M-". c .">"
endfor

" Filetypes
autocmd FileType vim setlocal expandtab shiftwidth=4 tabstop=8 softtabstop=4
autocmd FileType sh setlocal expandtab shiftwidth=4 tabstop=8 softtabstop=4
autocmd FileType ruby,scala setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType html,xhtml,xml setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType css setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType javascript setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
let javascript_enable_domhtmlcss=1
