#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#--------------------------------------------------------------------------------
# Fonts
#--------------------------------------------------------------------------------

xset +fp /usr/share/fonts/local
xset fp rehash

#--------------------------------------------------------------------------------
# X init
#--------------------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

DEFAULT_SESSION=awesome

case $1 in
    awesome)
        exec awesome
        ;;
    xfce4)
        exec startxfce4
        ;;
    *)
        exec $DEFAULT_SESSION
        ;;
esac

# exec gnome-session
# exec startkde
# ...or the Window Manager of your choice
#exec awesome
