#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#--------------------------------------------------------------------------------
# Fonts
#--------------------------------------------------------------------------------

xset +fp /usr/share/fonts/local
xset fp rehash

#--------------------------------------------------------------------------------
# X init
#--------------------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# exec gnome-session
# exec startkde
#exec startxfce4
# ...or the Window Manager of your choice
exec awesome
