export EDITOR="vim"
export VISUAL="vim"

#--------------------------------------------------------------------------------
# Path
#--------------------------------------------------------------------------------

PATH=~/scripts:~/bin:$PATH
path+=~/opt/android-studio/bin
path+=~/opt/idea/bin
path+=~/opt/gradle/bin
path+=~/opt/scala/bin
path+=~/.cabal/bin
path+=~/opt/ant/bin
path+=~/opt/Cloud9BrazilBuild-1.0/bin

#--------------------------------------------------------------------------------
# Local overrides
#--------------------------------------------------------------------------------

for f in ~/.zshenv_*
do
    source $f
done

#--------------------------------------------------------------------------------
# Path
#--------------------------------------------------------------------------------

# Add segments that depend on overrides here
path+=$ANDROID_SDK/tools
path+=$ANDROID_SDK/platform-tools

# Remove path duplicates
typeset -U PATH

# Remove any entries that don't exist
# http://stackoverflow.com/questions/9347478/how-to-edit-path-variable-in-zsh
path=($^path(N))

