# Helpful links:
# http://grml.org/zsh/zsh-lovers.html
# http://blog.andrewhays.net/love-your-terminal
# http://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/

#--------------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------------

# new commands
alias rezsh='source ~/.zshrc'
alias userls='cat /etc/passwd | cut -d: -f1 | sort'
alias groupls='cat /etc/group | cut -d: -f1 | sort'
alias pacup='sudo pacmatic -Syu'
alias svim='sudo -E vim'

# cd
alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

# ls
alias ls='ls --color'
alias la='ls -Ah'
alias ll='ls -lh'
alias lr='ls -tRh'
alias lt='ls -lth'
alias lal='la -l'
alias lla='lal'

# other
alias gw='./gradlew'

#--------------------------------------------------------------------------------
# History
#--------------------------------------------------------------------------------

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

#--------------------------------------------------------------------------------
# Completions
#--------------------------------------------------------------------------------

# Enable completions
autoload -Uz compinit
compinit

# Completion caching
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Ignore completion functions for commands you dont have
zstyle ':completion:*:functions' ignored-patterns '_*'

# Completing process IDs with menu selection
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always

# Fix slow git completions: http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () { _wanted files expl 'local files' _files }

#--------------------------------------------------------------------------------
# Key bindings
#--------------------------------------------------------------------------------

# Emacs editing mode
bindkey -e

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\ee[C" forward-word
bindkey "\ee[D" backward-word
#bindkey "^H" backward-delete-word
# for rxvt
bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix

# Alternate / much smaller solution to the same end by adding the following to your .zshrc:
# eval "$(sed -n 's/^/bindkey /; s/: / /p' /etc/inputrc)"

#--------------------------------------------------------------------------------
# CK2 
#--------------------------------------------------------------------------------

export CK2_SAVES=~/Documents/Paradox\ Interactive/Crusader\ Kings\ II/save\ games
export CK2_DROPBOX=~/Dropbox/games/CrusaderKings2

function ck2-save-latest {
  LATEST=`ls -t $CK2_SAVES/*.ck2 | head -n 1`
  cp $LATEST $CK2_DROPBOX
}

function ck2-load-latest {
  LATEST=`ls -t $CK2_DROPBOX/*.ck2 | head -n 1`
  cp $LATEST $CK2_SAVES
}

#--------------------------------------------------------------------------------
# Misc 
#--------------------------------------------------------------------------------

export BROWSER="chromium"
export EDITOR="vim"
export LESS="-r"
export PAGER="less"

# Extended globbing: http://zsh.sourceforge.net/Intro/intro_2.html
setopt extendedglob

# http://zsh.sourceforge.net/Doc/Release/Options.html
setopt auto_cd

# Prompt
autoload -U colors && colors
PS1="%{$fg[yellow]%}%n%{$reset_color%}@%{$fg[green]%}%m %{$fg[white]%}%~ %{$reset_color%}%% "

#--------------------------------------------------------------------------------
# CD bookmarks
#--------------------------------------------------------------------------------

# From http://ivan.fomentgroup.org/blog/2010/01/29/zsh-bookmarks-for-cd-change-directory-with-completion/
# function cdb_edit() { vim ~/.cdbookmarks }
# function cdb() { NewDir=`egrep "^$1<TAB_KEY>" ~/.cdbookmarks | sed 's/^.*<TAB_KEY>//'`; echo cd $NewDir; cd $NewDir }
# function _cdb() { reply=(`cat ~/.cdbookmarks | sed 's/<TAB_KEY>.*$//'`); }
# compctl -K _cdb cdb

#--------------------------------------------------------------------------------
# VirtualBox
#--------------------------------------------------------------------------------

alias vbm='VBoxManage $*'

#--------------------------------------------------------------------------------
# Boto / Git Annex
#--------------------------------------------------------------------------------

if [[ -e ~/.boto ]]; then
    export AWS_ACCESS_KEY_ID="$(cat ~/.boto | grep -i AWS_ACCESS_KEY_ID | sed 's/^.*=\s*//')"
    export AWS_SECRET_ACCESS_KEY="$(cat ~/.boto | grep -i AWS_SECRET_ACCESS_KEY | sed 's/^.*=\s*//')"
fi

#--------------------------------------------------------------------------------
# Finale
#--------------------------------------------------------------------------------

# Start @ home
cd

#--------------------------------------------------------------------------------
# GVM
#--------------------------------------------------------------------------------

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "~/.gvm/bin/gvm-init.sh" ]] && source "~/.gvm/bin/gvm-init.sh"
