# Helpful links:
# http://grml.org/zsh/zsh-lovers.html
# http://blog.andrewhays.net/love-your-terminal
# http://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/

#--------------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------------

# new commands
alias rezsh='source ~/.zshrc'
alias userls='cat /etc/passwd | cut -d: -f1 | sort'
alias groupls='cat /etc/group | cut -d: -f1 | sort'
alias pacup='sudo pacmatic -Syu'

# cd
alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

# ls
alias ls='ls --color'
alias la='ls -Ah'
alias ll='ls -lh'
alias lr='ls -tRh'
alias lt='ls -lth'

#--------------------------------------------------------------------------------
# History
#--------------------------------------------------------------------------------

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

#--------------------------------------------------------------------------------
# Completions
#--------------------------------------------------------------------------------

# Enable completions
autoload -Uz compinit
compinit

# Completion caching
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Ignore completion functions for commands you dont have
zstyle ':completion:*:functions' ignored-patterns '_*'

# Completing process IDs with menu selection
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always

# Fix slow git completions: http://talkings.org/post/5236392664/zsh-and-slow-git-completion
__git_files () { _wanted files expl 'local files' _files }

#--------------------------------------------------------------------------------
# Key bindings
#--------------------------------------------------------------------------------

# Emacs editing mode
bindkey -e

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\ee[C" forward-word
bindkey "\ee[D" backward-word
bindkey "^H" backward-delete-word
# for rxvt
bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix

# Alternate / much smaller solution to the same end by adding the following to your .zshrc:
# eval "$(sed -n 's/^/bindkey /; s/: / /p' /etc/inputrc)"

#--------------------------------------------------------------------------------
# Misc 
#--------------------------------------------------------------------------------

export LESS="-r"

# Extended globbing: http://zsh.sourceforge.net/Intro/intro_2.html
setopt extendedglob

# http://zsh.sourceforge.net/Doc/Release/Options.html
setopt auto_cd

# Prompt
autoload -U colors && colors
PS1="%{$fg[yellow]%}%n%{$reset_color%}@%{$fg[green]%}%m %{$fg[white]%}%~ %{$reset_color%}%% "

#--------------------------------------------------------------------------------
# Local overrides
#--------------------------------------------------------------------------------

if [[ -e ~/.zshrc_local ]]; then
    source ~/.zshrc_local
fi

#--------------------------------------------------------------------------------
# Path
#--------------------------------------------------------------------------------

# Add to path
path+=~/scripts

# Remove any entries that don't exist
# http://stackoverflow.com/questions/9347478/how-to-edit-path-variable-in-zsh
path=($^path(N))

#--------------------------------------------------------------------------------
# Finale
#--------------------------------------------------------------------------------

# Start @ home
cd
