export EOS='192.168.1.241'
export LUNA='192.168.1.35'

alias ck2='~/.local/share/Steam/SteamApps/common/Crusader\ Kings\ II/ck2'
alias matchmaker='java -jar ~/opt/misc/matchmaker.jar'

function licr { xhost +local: && su lim -lc 'export DISPLAY=":0.0" && chromium-browser' }

