#!/bin/sh
export AWS_ACCESS_KEY_ID=$(grep aws_access_key_id ~/.boto | cut -d ' ' -f 3)
export AWS_SECRET_ACCESS_KEY=$(grep aws_secret_access_key ~/.boto | cut -d ' ' -f 3)
~/opt/glacier-cli/glacier.py --region us-west-2 $*
