echo begin zshenv_p50

export ANDROID_SDK=/opt/android_sdk
export ANDROID_HOME=${ANDROID_SDK}
export ANDROID_NDK_REPOSITORY=/opt/android_ndk
export ANDROID_NDK=${ANDROID_NDK_REPOSITORY}/android-ndk-r10e

export PATH=/opt/fbhg/bin:${PATH}
path+=~/devtools/buck/bin
